const ActionTypes = {
    FLIP_CARD_UP: 'FLIP_CARD_UP',
    FLIP_CARD_DOWN: 'FLIP_CARD_DOWN',
    FLIP_ALL_DOWN: 'FLIP_ALL_DOWN',
    CONFIRM_PAIR: 'CONFIRM_PAIR',
    CHANGE_SCORE: 'CHANGE_SCORE',
    START_NEW_GAME: 'START_NEW_GAME',
    CHANGE_CHECKING_CARD: 'CHANGE_CHECKING_CARD',
    INITIAL_TIMER_END: 'INITIAL_TIMER_END',
    CHECK_TIMER_START: 'CHECK_TIMER_START',
    CHECK_TIMER_END: 'CHECK_TIMER_END'
};

export { ActionTypes };