const ActionTypes = {
    FLIP_CARD_UP: 'FLIP_CARD_UP',
    FLIP_CARD_DOWN: 'FLIP_CARD_DOWN',
    FLIP_ALL_DOWN: 'FLIP_ALL_DOWN',
    CONFIRM_CARD: 'CONFIRM_CARD',
    CHANGE_SCORE: 'CHANGE_SCORE',
    SET_CARDS: 'SET_CARDS',
    CHANGE_CHECKING_CARD: 'CHANGE_CHECKING_CARD'

};

export { ActionTypes };